// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: api/whywait.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----- EMPTY -----
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_whywait_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{0}
}

// ----- AUTH -----
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_whywait_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_whywait_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_whywait_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_whywait_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// ----- PASSENGER -----
type Terminal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Terminal) Reset() {
	*x = Terminal{}
	mi := &file_api_whywait_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminal) ProtoMessage() {}

func (x *Terminal) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminal.ProtoReflect.Descriptor instead.
func (*Terminal) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{5}
}

func (x *Terminal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Terminal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Terminal) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Terminal) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Terminal) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Terminal) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type TerminalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Terminals     []*Terminal            `protobuf:"bytes,2,rep,name=terminals,proto3" json:"terminals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalsResponse) Reset() {
	*x = TerminalsResponse{}
	mi := &file_api_whywait_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalsResponse) ProtoMessage() {}

func (x *TerminalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalsResponse.ProtoReflect.Descriptor instead.
func (*TerminalsResponse) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TerminalsResponse) GetTerminals() []*Terminal {
	if x != nil {
		return x.Terminals
	}
	return nil
}

type PopularRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	WaitTime      int32                  `protobuf:"varint,3,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularRoute) Reset() {
	*x = PopularRoute{}
	mi := &file_api_whywait_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularRoute) ProtoMessage() {}

func (x *PopularRoute) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularRoute.ProtoReflect.Descriptor instead.
func (*PopularRoute) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{7}
}

func (x *PopularRoute) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PopularRoute) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PopularRoute) GetWaitTime() int32 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

type PopularRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Routes        []*PopularRoute        `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularRoutesResponse) Reset() {
	*x = PopularRoutesResponse{}
	mi := &file_api_whywait_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularRoutesResponse) ProtoMessage() {}

func (x *PopularRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularRoutesResponse.ProtoReflect.Descriptor instead.
func (*PopularRoutesResponse) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{8}
}

func (x *PopularRoutesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PopularRoutesResponse) GetRoutes() []*PopularRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type TaxiStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Available      int32                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Total          int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	AverageWait    int32                  `protobuf:"varint,4,opt,name=average_wait,json=averageWait,proto3" json:"average_wait,omitempty"`
	NearbyStations int32                  `protobuf:"varint,5,opt,name=nearby_stations,json=nearbyStations,proto3" json:"nearby_stations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaxiStatusResponse) Reset() {
	*x = TaxiStatusResponse{}
	mi := &file_api_whywait_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxiStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxiStatusResponse) ProtoMessage() {}

func (x *TaxiStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxiStatusResponse.ProtoReflect.Descriptor instead.
func (*TaxiStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{9}
}

func (x *TaxiStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaxiStatusResponse) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *TaxiStatusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaxiStatusResponse) GetAverageWait() int32 {
	if x != nil {
		return x.AverageWait
	}
	return 0
}

func (x *TaxiStatusResponse) GetNearbyStations() int32 {
	if x != nil {
		return x.NearbyStations
	}
	return 0
}

// ----- REAL-TIME TRACKING -----
type TrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Station       string                 `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackRequest) Reset() {
	*x = TrackRequest{}
	mi := &file_api_whywait_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackRequest) ProtoMessage() {}

func (x *TrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackRequest.ProtoReflect.Descriptor instead.
func (*TrackRequest) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{10}
}

func (x *TrackRequest) GetStation() string {
	if x != nil {
		return x.Station
	}
	return ""
}

type TaxiUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxiId        string                 `protobuf:"bytes,1,opt,name=taxi_id,json=taxiId,proto3" json:"taxi_id,omitempty"`
	Plate         string                 `protobuf:"bytes,2,opt,name=plate,proto3" json:"plate,omitempty"`
	DriverName    string                 `protobuf:"bytes,3,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,7,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	EtaMinutes    int32                  `protobuf:"varint,8,opt,name=eta_minutes,json=etaMinutes,proto3" json:"eta_minutes,omitempty"`
	Station       string                 `protobuf:"bytes,9,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaxiUpdate) Reset() {
	*x = TaxiUpdate{}
	mi := &file_api_whywait_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxiUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxiUpdate) ProtoMessage() {}

func (x *TaxiUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxiUpdate.ProtoReflect.Descriptor instead.
func (*TaxiUpdate) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{11}
}

func (x *TaxiUpdate) GetTaxiId() string {
	if x != nil {
		return x.TaxiId
	}
	return ""
}

func (x *TaxiUpdate) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *TaxiUpdate) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *TaxiUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaxiUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TaxiUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TaxiUpdate) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *TaxiUpdate) GetEtaMinutes() int32 {
	if x != nil {
		return x.EtaMinutes
	}
	return 0
}

func (x *TaxiUpdate) GetStation() string {
	if x != nil {
		return x.Station
	}
	return ""
}

// ----- DRIVER -----
type LocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxiId        string                 `protobuf:"bytes,1,opt,name=taxi_id,json=taxiId,proto3" json:"taxi_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,5,opt,name=heading,proto3" json:"heading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_api_whywait_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{12}
}

func (x *LocationUpdate) GetTaxiId() string {
	if x != nil {
		return x.TaxiId
	}
	return ""
}

func (x *LocationUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationUpdate) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationUpdate) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type LocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationResponse) Reset() {
	*x = LocationResponse{}
	mi := &file_api_whywait_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResponse) ProtoMessage() {}

func (x *LocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResponse.ProtoReflect.Descriptor instead.
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{13}
}

func (x *LocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxiId        string                 `protobuf:"bytes,1,opt,name=taxi_id,json=taxiId,proto3" json:"taxi_id,omitempty"`
	IsOnline      bool                   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverStatusRequest) Reset() {
	*x = DriverStatusRequest{}
	mi := &file_api_whywait_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverStatusRequest) ProtoMessage() {}

func (x *DriverStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverStatusRequest.ProtoReflect.Descriptor instead.
func (*DriverStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{14}
}

func (x *DriverStatusRequest) GetTaxiId() string {
	if x != nil {
		return x.TaxiId
	}
	return ""
}

func (x *DriverStatusRequest) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

type DriverStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverStatusResponse) Reset() {
	*x = DriverStatusResponse{}
	mi := &file_api_whywait_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverStatusResponse) ProtoMessage() {}

func (x *DriverStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverStatusResponse.ProtoReflect.Descriptor instead.
func (*DriverStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{15}
}

func (x *DriverStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ----- ASSIGNED TAXIS -----
type AssignedTaxisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedTaxisRequest) Reset() {
	*x = AssignedTaxisRequest{}
	mi := &file_api_whywait_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedTaxisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedTaxisRequest) ProtoMessage() {}

func (x *AssignedTaxisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedTaxisRequest.ProtoReflect.Descriptor instead.
func (*AssignedTaxisRequest) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{16}
}

func (x *AssignedTaxisRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

type AssignedTaxiInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxiId        string                 `protobuf:"bytes,1,opt,name=taxi_id,json=taxiId,proto3" json:"taxi_id,omitempty"`
	Plate         string                 `protobuf:"bytes,2,opt,name=plate,proto3" json:"plate,omitempty"`
	DriverName    string                 `protobuf:"bytes,3,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,7,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	EtaMinutes    int32                  `protobuf:"varint,8,opt,name=eta_minutes,json=etaMinutes,proto3" json:"eta_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedTaxiInfo) Reset() {
	*x = AssignedTaxiInfo{}
	mi := &file_api_whywait_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedTaxiInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedTaxiInfo) ProtoMessage() {}

func (x *AssignedTaxiInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedTaxiInfo.ProtoReflect.Descriptor instead.
func (*AssignedTaxiInfo) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{17}
}

func (x *AssignedTaxiInfo) GetTaxiId() string {
	if x != nil {
		return x.TaxiId
	}
	return ""
}

func (x *AssignedTaxiInfo) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *AssignedTaxiInfo) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *AssignedTaxiInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignedTaxiInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AssignedTaxiInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AssignedTaxiInfo) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *AssignedTaxiInfo) GetEtaMinutes() int32 {
	if x != nil {
		return x.EtaMinutes
	}
	return 0
}

type AssignedTaxisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taxis         []*AssignedTaxiInfo    `protobuf:"bytes,1,rep,name=taxis,proto3" json:"taxis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedTaxisResponse) Reset() {
	*x = AssignedTaxisResponse{}
	mi := &file_api_whywait_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedTaxisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedTaxisResponse) ProtoMessage() {}

func (x *AssignedTaxisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whywait_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedTaxisResponse.ProtoReflect.Descriptor instead.
func (*AssignedTaxisResponse) Descriptor() ([]byte, []int) {
	return file_api_whywait_proto_rawDescGZIP(), []int{18}
}

func (x *AssignedTaxisResponse) GetTaxis() []*AssignedTaxiInfo {
	if x != nil {
		return x.Taxis
	}
	return nil
}

var File_api_whywait_proto protoreflect.FileDescriptor

const file_api_whywait_proto_rawDesc = "" +
	"\n" +
	"\x11api/whywait.proto\x12\awhywait\"\a\n" +
	"\x05Empty\"v\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"a\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\r.whywait.UserR\x04user\"s\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x96\x01\n" +
	"\bTerminal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\"^\n" +
	"\x11TerminalsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\tterminals\x18\x02 \x03(\v2\x11.whywait.TerminalR\tterminals\"O\n" +
	"\fPopularRoute\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1b\n" +
	"\twait_time\x18\x03 \x01(\x05R\bwaitTime\"`\n" +
	"\x15PopularRoutesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x06routes\x18\x02 \x03(\v2\x15.whywait.PopularRouteR\x06routes\"\xae\x01\n" +
	"\x12TaxiStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x05R\tavailable\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12!\n" +
	"\faverage_wait\x18\x04 \x01(\x05R\vaverageWait\x12'\n" +
	"\x0fnearby_stations\x18\x05 \x01(\x05R\x0enearbyStations\"(\n" +
	"\fTrackRequest\x12\x18\n" +
	"\astation\x18\x01 \x01(\tR\astation\"\x8a\x02\n" +
	"\n" +
	"TaxiUpdate\x12\x17\n" +
	"\ataxi_id\x18\x01 \x01(\tR\x06taxiId\x12\x14\n" +
	"\x05plate\x18\x02 \x01(\tR\x05plate\x12\x1f\n" +
	"\vdriver_name\x18\x03 \x01(\tR\n" +
	"driverName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vdistance_km\x18\a \x01(\x01R\n" +
	"distanceKm\x12\x1f\n" +
	"\veta_minutes\x18\b \x01(\x05R\n" +
	"etaMinutes\x12\x18\n" +
	"\astation\x18\t \x01(\tR\astation\"\x93\x01\n" +
	"\x0eLocationUpdate\x12\x17\n" +
	"\ataxi_id\x18\x01 \x01(\tR\x06taxiId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x05 \x01(\x01R\aheading\"F\n" +
	"\x10LocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x13DriverStatusRequest\x12\x17\n" +
	"\ataxi_id\x18\x01 \x01(\tR\x06taxiId\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\bR\bisOnline\"J\n" +
	"\x14DriverStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x14AssignedTaxisRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\"\xf6\x01\n" +
	"\x10AssignedTaxiInfo\x12\x17\n" +
	"\ataxi_id\x18\x01 \x01(\tR\x06taxiId\x12\x14\n" +
	"\x05plate\x18\x02 \x01(\tR\x05plate\x12\x1f\n" +
	"\vdriver_name\x18\x03 \x01(\tR\n" +
	"driverName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vdistance_km\x18\a \x01(\x01R\n" +
	"distanceKm\x12\x1f\n" +
	"\veta_minutes\x18\b \x01(\x05R\n" +
	"etaMinutes\"H\n" +
	"\x15AssignedTaxisResponse\x12/\n" +
	"\x05taxis\x18\x01 \x03(\v2\x19.whywait.AssignedTaxiInfoR\x05taxis2\xe7\x04\n" +
	"\vTaxiService\x12;\n" +
	"\bRegister\x12\x18.whywait.RegisterRequest\x1a\x15.whywait.AuthResponse\x125\n" +
	"\x05Login\x12\x15.whywait.LoginRequest\x1a\x15.whywait.AuthResponse\x12:\n" +
	"\fGetTerminals\x12\x0e.whywait.Empty\x1a\x1a.whywait.TerminalsResponse\x12B\n" +
	"\x10GetPopularRoutes\x12\x0e.whywait.Empty\x1a\x1e.whywait.PopularRoutesResponse\x12<\n" +
	"\rGetTaxiStatus\x12\x0e.whywait.Empty\x1a\x1b.whywait.TaxiStatusResponse\x12:\n" +
	"\n" +
	"TrackTaxis\x12\x15.whywait.TrackRequest\x1a\x13.whywait.TaxiUpdate0\x01\x12D\n" +
	"\x0eUpdateLocation\x12\x17.whywait.LocationUpdate\x1a\x19.whywait.LocationResponse\x12Q\n" +
	"\x12UpdateDriverStatus\x12\x1c.whywait.DriverStatusRequest\x1a\x1d.whywait.DriverStatusResponse\x12Q\n" +
	"\x10GetAssignedTaxis\x12\x1d.whywait.AssignedTaxisRequest\x1a\x1e.whywait.AssignedTaxisResponseB\x15Z\x13whywait-backend/apib\x06proto3"

var (
	file_api_whywait_proto_rawDescOnce sync.Once
	file_api_whywait_proto_rawDescData []byte
)

func file_api_whywait_proto_rawDescGZIP() []byte {
	file_api_whywait_proto_rawDescOnce.Do(func() {
		file_api_whywait_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_whywait_proto_rawDesc), len(file_api_whywait_proto_rawDesc)))
	})
	return file_api_whywait_proto_rawDescData
}

var file_api_whywait_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_whywait_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: whywait.Empty
	(*RegisterRequest)(nil),       // 1: whywait.RegisterRequest
	(*LoginRequest)(nil),          // 2: whywait.LoginRequest
	(*AuthResponse)(nil),          // 3: whywait.AuthResponse
	(*User)(nil),                  // 4: whywait.User
	(*Terminal)(nil),              // 5: whywait.Terminal
	(*TerminalsResponse)(nil),     // 6: whywait.TerminalsResponse
	(*PopularRoute)(nil),          // 7: whywait.PopularRoute
	(*PopularRoutesResponse)(nil), // 8: whywait.PopularRoutesResponse
	(*TaxiStatusResponse)(nil),    // 9: whywait.TaxiStatusResponse
	(*TrackRequest)(nil),          // 10: whywait.TrackRequest
	(*TaxiUpdate)(nil),            // 11: whywait.TaxiUpdate
	(*LocationUpdate)(nil),        // 12: whywait.LocationUpdate
	(*LocationResponse)(nil),      // 13: whywait.LocationResponse
	(*DriverStatusRequest)(nil),   // 14: whywait.DriverStatusRequest
	(*DriverStatusResponse)(nil),  // 15: whywait.DriverStatusResponse
	(*AssignedTaxisRequest)(nil),  // 16: whywait.AssignedTaxisRequest
	(*AssignedTaxiInfo)(nil),      // 17: whywait.AssignedTaxiInfo
	(*AssignedTaxisResponse)(nil), // 18: whywait.AssignedTaxisResponse
}
var file_api_whywait_proto_depIdxs = []int32{
	4,  // 0: whywait.AuthResponse.user:type_name -> whywait.User
	5,  // 1: whywait.TerminalsResponse.terminals:type_name -> whywait.Terminal
	7,  // 2: whywait.PopularRoutesResponse.routes:type_name -> whywait.PopularRoute
	17, // 3: whywait.AssignedTaxisResponse.taxis:type_name -> whywait.AssignedTaxiInfo
	1,  // 4: whywait.TaxiService.Register:input_type -> whywait.RegisterRequest
	2,  // 5: whywait.TaxiService.Login:input_type -> whywait.LoginRequest
	0,  // 6: whywait.TaxiService.GetTerminals:input_type -> whywait.Empty
	0,  // 7: whywait.TaxiService.GetPopularRoutes:input_type -> whywait.Empty
	0,  // 8: whywait.TaxiService.GetTaxiStatus:input_type -> whywait.Empty
	10, // 9: whywait.TaxiService.TrackTaxis:input_type -> whywait.TrackRequest
	12, // 10: whywait.TaxiService.UpdateLocation:input_type -> whywait.LocationUpdate
	14, // 11: whywait.TaxiService.UpdateDriverStatus:input_type -> whywait.DriverStatusRequest
	16, // 12: whywait.TaxiService.GetAssignedTaxis:input_type -> whywait.AssignedTaxisRequest
	3,  // 13: whywait.TaxiService.Register:output_type -> whywait.AuthResponse
	3,  // 14: whywait.TaxiService.Login:output_type -> whywait.AuthResponse
	6,  // 15: whywait.TaxiService.GetTerminals:output_type -> whywait.TerminalsResponse
	8,  // 16: whywait.TaxiService.GetPopularRoutes:output_type -> whywait.PopularRoutesResponse
	9,  // 17: whywait.TaxiService.GetTaxiStatus:output_type -> whywait.TaxiStatusResponse
	11, // 18: whywait.TaxiService.TrackTaxis:output_type -> whywait.TaxiUpdate
	13, // 19: whywait.TaxiService.UpdateLocation:output_type -> whywait.LocationResponse
	15, // 20: whywait.TaxiService.UpdateDriverStatus:output_type -> whywait.DriverStatusResponse
	18, // 21: whywait.TaxiService.GetAssignedTaxis:output_type -> whywait.AssignedTaxisResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_whywait_proto_init() }
func file_api_whywait_proto_init() {
	if File_api_whywait_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_whywait_proto_rawDesc), len(file_api_whywait_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_whywait_proto_goTypes,
		DependencyIndexes: file_api_whywait_proto_depIdxs,
		MessageInfos:      file_api_whywait_proto_msgTypes,
	}.Build()
	File_api_whywait_proto = out.File
	file_api_whywait_proto_goTypes = nil
	file_api_whywait_proto_depIdxs = nil
}
