// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: api/whywait.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaxiService_Register_FullMethodName           = "/whywait.TaxiService/Register"
	TaxiService_Login_FullMethodName              = "/whywait.TaxiService/Login"
	TaxiService_GetTerminals_FullMethodName       = "/whywait.TaxiService/GetTerminals"
	TaxiService_GetPopularRoutes_FullMethodName   = "/whywait.TaxiService/GetPopularRoutes"
	TaxiService_GetTaxiStatus_FullMethodName      = "/whywait.TaxiService/GetTaxiStatus"
	TaxiService_TrackTaxis_FullMethodName         = "/whywait.TaxiService/TrackTaxis"
	TaxiService_UpdateLocation_FullMethodName     = "/whywait.TaxiService/UpdateLocation"
	TaxiService_UpdateDriverStatus_FullMethodName = "/whywait.TaxiService/UpdateDriverStatus"
)

// TaxiServiceClient is the client API for TaxiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaxiServiceClient interface {
	// ===== AUTH =====
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// ===== PASSENGER =====
	GetTerminals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TerminalsResponse, error)
	GetPopularRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PopularRoutesResponse, error)
	GetTaxiStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaxiStatusResponse, error)
	// ===== REAL-TIME TRACKING (Server Streaming) =====
	TrackTaxis(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaxiUpdate], error)
	// ===== DRIVER =====
	UpdateLocation(ctx context.Context, in *LocationUpdate, opts ...grpc.CallOption) (*LocationResponse, error)
	UpdateDriverStatus(ctx context.Context, in *DriverStatusRequest, opts ...grpc.CallOption) (*DriverStatusResponse, error)
}

type taxiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaxiServiceClient(cc grpc.ClientConnInterface) TaxiServiceClient {
	return &taxiServiceClient{cc}
}

func (c *taxiServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, TaxiService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxiServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, TaxiService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxiServiceClient) GetTerminals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TerminalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminalsResponse)
	err := c.cc.Invoke(ctx, TaxiService_GetTerminals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxiServiceClient) GetPopularRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PopularRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PopularRoutesResponse)
	err := c.cc.Invoke(ctx, TaxiService_GetPopularRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxiServiceClient) GetTaxiStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaxiStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxiStatusResponse)
	err := c.cc.Invoke(ctx, TaxiService_GetTaxiStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxiServiceClient) TrackTaxis(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaxiUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaxiService_ServiceDesc.Streams[0], TaxiService_TrackTaxis_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackRequest, TaxiUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaxiService_TrackTaxisClient = grpc.ServerStreamingClient[TaxiUpdate]

func (c *taxiServiceClient) UpdateLocation(ctx context.Context, in *LocationUpdate, opts ...grpc.CallOption) (*LocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, TaxiService_UpdateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxiServiceClient) UpdateDriverStatus(ctx context.Context, in *DriverStatusRequest, opts ...grpc.CallOption) (*DriverStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverStatusResponse)
	err := c.cc.Invoke(ctx, TaxiService_UpdateDriverStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaxiServiceServer is the server API for TaxiService service.
// All implementations must embed UnimplementedTaxiServiceServer
// for forward compatibility.
type TaxiServiceServer interface {
	// ===== AUTH =====
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	// ===== PASSENGER =====
	GetTerminals(context.Context, *Empty) (*TerminalsResponse, error)
	GetPopularRoutes(context.Context, *Empty) (*PopularRoutesResponse, error)
	GetTaxiStatus(context.Context, *Empty) (*TaxiStatusResponse, error)
	// ===== REAL-TIME TRACKING (Server Streaming) =====
	TrackTaxis(*TrackRequest, grpc.ServerStreamingServer[TaxiUpdate]) error
	// ===== DRIVER =====
	UpdateLocation(context.Context, *LocationUpdate) (*LocationResponse, error)
	UpdateDriverStatus(context.Context, *DriverStatusRequest) (*DriverStatusResponse, error)
	mustEmbedUnimplementedTaxiServiceServer()
}

// UnimplementedTaxiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaxiServiceServer struct{}

func (UnimplementedTaxiServiceServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedTaxiServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedTaxiServiceServer) GetTerminals(context.Context, *Empty) (*TerminalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTerminals not implemented")
}
func (UnimplementedTaxiServiceServer) GetPopularRoutes(context.Context, *Empty) (*PopularRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularRoutes not implemented")
}
func (UnimplementedTaxiServiceServer) GetTaxiStatus(context.Context, *Empty) (*TaxiStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaxiStatus not implemented")
}
func (UnimplementedTaxiServiceServer) TrackTaxis(*TrackRequest, grpc.ServerStreamingServer[TaxiUpdate]) error {
	return status.Error(codes.Unimplemented, "method TrackTaxis not implemented")
}
func (UnimplementedTaxiServiceServer) UpdateLocation(context.Context, *LocationUpdate) (*LocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedTaxiServiceServer) UpdateDriverStatus(context.Context, *DriverStatusRequest) (*DriverStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDriverStatus not implemented")
}
func (UnimplementedTaxiServiceServer) mustEmbedUnimplementedTaxiServiceServer() {}
func (UnimplementedTaxiServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaxiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaxiServiceServer will
// result in compilation errors.
type UnsafeTaxiServiceServer interface {
	mustEmbedUnimplementedTaxiServiceServer()
}

func RegisterTaxiServiceServer(s grpc.ServiceRegistrar, srv TaxiServiceServer) {
	// If the following call panics, it indicates UnimplementedTaxiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaxiService_ServiceDesc, srv)
}

func _TaxiService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxiServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxiService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxiServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxiService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxiServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxiService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxiServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxiService_GetTerminals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxiServiceServer).GetTerminals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxiService_GetTerminals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxiServiceServer).GetTerminals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxiService_GetPopularRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxiServiceServer).GetPopularRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxiService_GetPopularRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxiServiceServer).GetPopularRoutes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxiService_GetTaxiStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxiServiceServer).GetTaxiStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxiService_GetTaxiStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxiServiceServer).GetTaxiStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxiService_TrackTaxis_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaxiServiceServer).TrackTaxis(m, &grpc.GenericServerStream[TrackRequest, TaxiUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaxiService_TrackTaxisServer = grpc.ServerStreamingServer[TaxiUpdate]

func _TaxiService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxiServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxiService_UpdateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxiServiceServer).UpdateLocation(ctx, req.(*LocationUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxiService_UpdateDriverStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxiServiceServer).UpdateDriverStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxiService_UpdateDriverStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxiServiceServer).UpdateDriverStatus(ctx, req.(*DriverStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaxiService_ServiceDesc is the grpc.ServiceDesc for TaxiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaxiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whywait.TaxiService",
	HandlerType: (*TaxiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TaxiService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _TaxiService_Login_Handler,
		},
		{
			MethodName: "GetTerminals",
			Handler:    _TaxiService_GetTerminals_Handler,
		},
		{
			MethodName: "GetPopularRoutes",
			Handler:    _TaxiService_GetPopularRoutes_Handler,
		},
		{
			MethodName: "GetTaxiStatus",
			Handler:    _TaxiService_GetTaxiStatus_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _TaxiService_UpdateLocation_Handler,
		},
		{
			MethodName: "UpdateDriverStatus",
			Handler:    _TaxiService_UpdateDriverStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackTaxis",
			Handler:       _TaxiService_TrackTaxis_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/whywait.proto",
}
